apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: example/nginx
  name: nginx
  namespace: nginx
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|example|nginx'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: main
        image: "nginx:1.14.2:"
